version: "3"

services:
  fastapi_app:
    build:
      context: .            
      dockerfile: Dockerfile

    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:ajay123@db/mydb
    # deploy:
    #   replicas: 2   


  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: ajay123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
