global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    static_configs:
      - targets: ["fastapi_app:8000"]

  - job_name: "worker"
    static_configs:
      - targets: ["worker:8001"]
